// react-project/src/components/List.js
import Badge from "./Badge";
import Input from "./Input";
import {useMemo} from "react";

function List({categories, selected, setSelected, query, setQuery}) {

    const selectedCategories = useMemo(() => {
        console.log('selectedCategories')
        return selected.map(catId => categories.find(c => c.id === catId))
    }, [selected])

    const toggleSelected = category => {
        if (selected.includes(category.id)) {
            setSelected(selected.filter(catId => catId !== category.id))
        } else {
            setSelected([...selected, category.id])
        }
    }

    return (
        <>

            <section>

                <Input query={query} setQuery={setQuery}/>

                <h3>Selected Categories</h3>
                {selectedCategories.map(category => (
                    <Badge category={category} key={category.id} toggleSelected={toggleSelected}/>
                ))}
            </section>

            <section>
                <h3>Categories</h3>
                {categories.map(category => (
                    <button onClick={() => toggleSelected(category)}
                            className={selected.includes(category.id) ? 'active' : ''}
                            key={category.id}>{category.title}</button>
                ))}
            </section>

            <style>{`
              button.active {
                background: orangered;
                color: #fff;
              }
            `}</style>

        </>
    )
}

export default List

// svelte-project/src/components/List.svelte
<script>
    import Badge from "./Badge.svelte";
    import Input from "./Input.svelte";

    export let categories
    export let selected
    export let query

    $: selectedCategories = selected.map(catId => categories.find(c => c.id === catId))

    const toggleSelected = category => {
        if (selected.includes(category.id)) {
            selected = selected.filter(catId => catId !== category.id)
        } else {
            selected = [...selected, category.id]
        }
    }
</script>

<section>
    <Input bind:query={query} />
    {query}
    <h3>Selected Categories</h3>
    {#if selectedCategories.length}
        {#each selectedCategories as category (category.id)}
            <Badge toggleSelected={toggleSelected} category={category}/>
        {/each}
    {:else}
        No category selected..
    {/if}
</section>

<section>
    <h3>Categories</h3>
    {#each categories as category (category.id)}
        <button on:click={() => toggleSelected(category)} class:active={selected.includes(category.id)}>
            {category.title}
        </button>
    {/each}
</section>

<style>
    button.active {
        background: orangered;
        color: #fff;
    }
</style>
